// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: registry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentRegistryClient is the client API for AgentRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentRegistryClient interface {
	RegisterAgent(ctx context.Context, in *AgentRegistration, opts ...grpc.CallOption) (*RegistrationResponse, error)
}

type agentRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRegistryClient(cc grpc.ClientConnInterface) AgentRegistryClient {
	return &agentRegistryClient{cc}
}

func (c *agentRegistryClient) RegisterAgent(ctx context.Context, in *AgentRegistration, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, "/gAgentsRegistry.AgentRegistry/RegisterAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentRegistryServer is the server API for AgentRegistry service.
// All implementations must embed UnimplementedAgentRegistryServer
// for forward compatibility
type AgentRegistryServer interface {
	RegisterAgent(context.Context, *AgentRegistration) (*RegistrationResponse, error)
	mustEmbedUnimplementedAgentRegistryServer()
}

// UnimplementedAgentRegistryServer must be embedded to have forward compatible implementations.
type UnimplementedAgentRegistryServer struct {
}

func (UnimplementedAgentRegistryServer) RegisterAgent(context.Context, *AgentRegistration) (*RegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedAgentRegistryServer) mustEmbedUnimplementedAgentRegistryServer() {}

// UnsafeAgentRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRegistryServer will
// result in compilation errors.
type UnsafeAgentRegistryServer interface {
	mustEmbedUnimplementedAgentRegistryServer()
}

func RegisterAgentRegistryServer(s grpc.ServiceRegistrar, srv AgentRegistryServer) {
	s.RegisterService(&AgentRegistry_ServiceDesc, srv)
}

func _AgentRegistry_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRegistryServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gAgentsRegistry.AgentRegistry/RegisterAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRegistryServer).RegisterAgent(ctx, req.(*AgentRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentRegistry_ServiceDesc is the grpc.ServiceDesc for AgentRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gAgentsRegistry.AgentRegistry",
	HandlerType: (*AgentRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _AgentRegistry_RegisterAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
